### ISSUE TITLE
How to run it?

### ISSUE THREAD

**Issue by chuanqi305** [ls1xt/deepdecoder#2]
@berleon 
Hi ,I have download your code ,but found that something is missing such as GeneratedGridTrainer, so it can not run. Your code is very useful for me, please upload the full edition and the documents, thank you.

**Comment by avisingh599** [comment]
"+ 1" for uploading instructions on how to use the code.

**Comment by andycui97** [comment]
+1, would love to learn how to use the code.

**Comment by ls1xt** [comment]
Hi, thanks for you all for your interest and please excuse my late reply. I have uploaded the necessary data. A dockerfile is available to reproduce my environment.  And a description on how to set everything up can be found in the README. If you have any questions, please ask me. Cheers, Leon
